export const demoSenders = [
  {
    email: "jobs-noreply@linkedin.com",
    name: "LinkedIn Jobs",
    count: 428,
    unread: 31,
    protectedCount: 4,
    accountCount: 1,
    latestAt: Date.now() - 35 * 60 * 1000,
  },
  {
    email: "alerts@zerodha.com",
    name: "Zerodha",
    count: 214,
    unread: 8,
    protectedCount: 2,
    accountCount: 1,
    latestAt: Date.now() - 3 * 60 * 60 * 1000,
  },
  {
    email: "newsletter@medium.com",
    name: "Medium Daily Digest",
    count: 187,
    unread: 42,
    protectedCount: 0,
    accountCount: 1,
    latestAt: Date.now() - 7 * 60 * 60 * 1000,
  },
  {
    email: "offers@amazon.in",
    name: "Amazon Offers",
    count: 154,
    unread: 17,
    protectedCount: 1,
    accountCount: 1,
    latestAt: Date.now() - 25 * 60 * 60 * 1000,
  },
  {
    email: "notifications@github.com",
    name: "GitHub",
    count: 96,
    unread: 5,
    protectedCount: 12,
    accountCount: 1,
    latestAt: Date.now() - 29 * 60 * 60 * 1000,
  },
  {
    email: "hello@swiggy.in",
    name: "Swiggy",
    count: 73,
    unread: 11,
    protectedCount: 0,
    accountCount: 1,
    latestAt: Date.now() - 49 * 60 * 60 * 1000,
  },
];

export const demoMessages = [
  {
    id: "demo-1",
    subject: "12 new roles match your preferences",
    receivedAt: Date.now() - 35 * 60 * 1000,
    isUnread: true,
    isStarred: false,
    isImportant: false,
    accountEmail: "demo@gmail.com",
    preview: "New frontend and product engineering roles were added in Bengaluru, including several positions that match your saved salary and experience preferences.",
  },
  {
    id: "demo-2",
    subject: "Senior frontend opportunities in Bengaluru",
    receivedAt: Date.now() - 26 * 60 * 60 * 1000,
    isUnread: false,
    isStarred: true,
    isImportant: false,
    accountEmail: "demo@gmail.com",
    preview: "Take a look at senior React, design systems, and platform engineering openings from companies hiring in Bengaluru this week.",
  },
  {
    id: "demo-3",
    subject: "Your weekly job search summary",
    receivedAt: Date.now() - 51 * 60 * 60 * 1000,
    isUnread: false,
    isStarred: false,
    isImportant: false,
    accountEmail: "demo@gmail.com",
    preview: "Your searches generated 86 new matches this week. The most active categories were frontend engineering, product development, and full-stack roles.",
  },
  {
    id: "demo-4",
    subject: "Companies are viewing profiles like yours",
    receivedAt: Date.now() - 4 * 24 * 60 * 60 * 1000,
    isUnread: false,
    isStarred: false,
    isImportant: false,
    accountEmail: "demo@gmail.com",
    preview: "Recruiters in technology and financial services searched for candidates with skills similar to yours. Refresh your profile to improve visibility.",
  },
  {
    id: "demo-5",
    subject: "5 remote roles you may have missed",
    receivedAt: Date.now() - 6 * 24 * 60 * 60 * 1000,
    isUnread: true,
    isStarred: false,
    isImportant: false,
    accountEmail: "demo@gmail.com",
    preview: "These remote-friendly positions are still accepting applications, with openings across frontend, full-stack, and developer experience teams.",
  },
  {
    id: "demo-6",
    subject: "Your application activity this month",
    receivedAt: Date.now() - 9 * 24 * 60 * 60 * 1000,
    isUnread: false,
    isStarred: false,
    isImportant: false,
    accountEmail: "demo@gmail.com",
    preview: "You viewed 24 jobs and saved 7 opportunities this month. Revisit saved roles before their application windows close.",
  },
  {
    id: "demo-7",
    subject: "New roles at fast-growing startups",
    receivedAt: Date.now() - 12 * 24 * 60 * 60 * 1000,
    isUnread: false,
    isStarred: false,
    isImportant: false,
    accountEmail: "demo@gmail.com",
    preview: "Explore engineering roles at recently funded startups building products in commerce, developer tools, AI, and financial technology.",
  },
  {
    id: "demo-8",
    subject: "Update your preferences for better matches",
    receivedAt: Date.now() - 15 * 24 * 60 * 60 * 1000,
    isUnread: false,
    isStarred: false,
    isImportant: true,
    accountEmail: "demo@gmail.com",
    preview: "Tell us which locations, role levels, and work arrangements you prefer so future job alerts contain fewer irrelevant recommendations.",
  },
  {
    id: "demo-9",
    subject: "Hiring is active for your saved search",
    receivedAt: Date.now() - 18 * 24 * 60 * 60 * 1000,
    isUnread: false,
    isStarred: false,
    isImportant: false,
    accountEmail: "demo@gmail.com",
    preview: "Several employers posted new openings matching your saved frontend engineer search during the past 24 hours.",
  },
  {
    id: "demo-10",
    subject: "Welcome to your personalized job alerts",
    receivedAt: Date.now() - 21 * 24 * 60 * 60 * 1000,
    isUnread: false,
    isStarred: false,
    isImportant: false,
    accountEmail: "demo@gmail.com",
    preview: "We’ll send recommendations based on your profile, searches, and saved jobs. You can change the alert frequency at any time.",
  },
];
